"""Read the OKF bundle: its concepts, and the ontology terms their frontmatter refers to.

    python -m xbpei.bundle check
    python -m xbpei.bundle affected xbpei:holdingCapacity
    python -m xbpei.bundle glossary computations/effective-holding
"""
import json
import os
import re
import sys
from dataclasses import dataclass
from functools import lru_cache

import yaml

from . import BUNDLE, MODEL
from .ontology import curie, describe_term, kind, to_iri, version

RESERVED = {"index.md", "log.md"}
GLOSSARY = "\n# Glossary\n"


@dataclass
class Concept:
    id: str
    meta: dict
    body: str

    @property
    def computation(self) -> str:
        """The single fenced block under `# Computation`."""
        section = self.body.split("# Computation", 1)[1]
        return re.search(r"```\w*\n(.*?)\n```", section, re.S).group(1)


def resolve(path: str, from_id: str = "") -> str:
    """Concept ID or bundle-relative file path for a bundle-relative or relative path."""
    if path.startswith("/"):
        target = BUNDLE / path[1:]
    else:
        target = (BUNDLE / from_id).parent / path
    return str(target.resolve().relative_to(BUNDLE.resolve())).removesuffix(".md")


@lru_cache
def concepts() -> dict[str, Concept]:
    found = {}
    for path in sorted(BUNDLE.rglob("*.md")):
        if path.name in RESERVED:
            continue
        _, front, body = path.read_text().split("---\n", 2)
        concept_id = str(path.relative_to(BUNDLE)).removesuffix(".md")
        found[concept_id] = Concept(concept_id, yaml.safe_load(front), body)
    return found


def concept(concept_id: str) -> Concept:
    return concepts()[concept_id.strip("/").removesuffix(".md")]


def terms_used() -> dict[str, set[str]]:
    """Ontology terms each concept reads or writes."""
    return {c.id: {curie(to_iri(t)) for t in c.meta.get("reads", []) + c.meta.get("writes", [])} for c in concepts().values()}


def affected_by(term: str) -> dict:
    """The computations and tools that read or write a term, and the procedure steps that use them."""
    term = curie(to_iri(term))
    direct = {c for c, terms in terms_used().items() if term in terms}
    steps = []
    for proc in concepts().values():
        for step in proc.meta.get("steps", []):
            used = sorted(direct & {resolve(u, proc.id) for u in step.get("uses", [])})
            if used:
                steps.append({"procedure": proc.id, "step": step["id"], "title": step["title"], "through": used})
    return {"term": term, "concepts": sorted(direct), "steps": steps}


def glossary(concept_id: str) -> str:
    """The ontology's meaning of each term a concept reads or writes, as the body of its `# Glossary` section."""
    c, rows = concept(concept_id), []
    for term in dict.fromkeys(c.meta.get("reads", []) + c.meta.get("writes", [])):
        d = describe_term(term)
        meaning = [d["definition"], d.get("scope_note", "")]
        meaning += [f"Kind of `{parent}`." for parent in d.get("kinds_of", [])]
        if "of" in d:
            meaning.append("Of " + ", ".join(f"`{owner}`" for owner in d["of"]) + ".")
            rng = d.get("range")
            meaning.append(f"Allowed: {', '.join(rng)}." if isinstance(rng, list) else f"Value: `{rng}`." if rng else "")
        cells = [f"`{term}`", d["kind"], " ".join(m for m in meaning if m), d.get("status", ""), d.get("steward", "")]
        rows.append("| " + " | ".join(cell.replace("|", "\\|") for cell in cells) + " |")
    model = os.path.relpath(MODEL, (BUNDLE / c.id).parent)
    head = [f"Meanings from ontology version {version()}, [{MODEL.name}]({model}), for the terms in `reads` and `writes`. Generated by `xbpei/bundle.py`; do not edit.", "",
            "| Term | Kind | Meaning | Status | Steward |", "|---|---|---|---|---|"]
    return "\n".join(head + rows)


def write_glossary(concept_id: str) -> None:
    """Add or refresh the `# Glossary` section, the last section of the concept's file."""
    path = BUNDLE / f"{concept(concept_id).id}.md"
    body = path.read_text().split(GLOSSARY)[0].rstrip("\n")
    path.write_text(f"{body}\n{GLOSSARY}\n{glossary(concept_id)}\n")


def check() -> list[str]:
    problems = []
    for c in concepts().values():
        if not c.meta.get("type"):
            problems.append(f"{c.id}: no type")
        for term in c.meta.get("reads", []) + c.meta.get("writes", []):
            if kind(to_iri(term)) is None:
                problems.append(f"{c.id}: {term} is not in the ontology")
        paths = [u for s in c.meta.get("steps", []) for u in s.get("uses", [])]
        paths += [c.meta[k]["resource"] for k in ("executor", "attester") if k in c.meta]
        paths += re.findall(r"\]\((/[^)]+)\)", c.body)
        for path in paths:
            if not (BUNDLE / resolve(path, c.id)).exists() and resolve(path, c.id) not in concepts():
                problems.append(f"{c.id}: {path} does not resolve")
        if c.meta.get("type") == "Attested Computation":
            declared = {p["name"] for p in c.meta["parameters"]}
            used = set(re.findall(r"%\((\w+)\)s|\$(\w+)", c.computation))
            used = {a or b for a, b in used}
            if used != declared:
                problems.append(f"{c.id}: computation binds {sorted(used)}, declares {sorted(declared)}")
        if GLOSSARY in c.body and c.body.split(GLOSSARY)[1].strip() != glossary(c.id):
            problems.append(f"{c.id}: glossary is out of date with the ontology")
    return problems


if __name__ == "__main__":
    if sys.argv[1] == "check":
        found = check()
        print("\n".join(found) if found else f"Bundle is consistent: {len(concepts())} concepts.")
        sys.exit(1 if found else 0)
    if sys.argv[1] == "glossary":
        write_glossary(sys.argv[2])
        sys.exit(0)
    print(json.dumps(affected_by(sys.argv[2]), indent=2))
